### ISSUE TITLE
TypeError: 'collections.OrderedDict' object is not callable

### ISSUE THREAD

**Issue by tigerneil** [berkeley-reclab/RecLab#216]
![image](https://user-images.githubusercontent.com/5799436/113991487-15475200-9885-11eb-9cf8-e05f40dc661a.png)

Today I tried the demo, found the above typeerror message. Any comment?

**Comment by pauldebdeep9** [comment]
I have also encountered the same issue. I am using python 3.8. 

Traceback (most recent call last):

  File "C:\Users\paul_\Documents\RecommendationEngine\RecLab-master\RecLab-master\SimpleDemo210512.py", line 13, in <module>
    online_users = env.online_users()

TypeError: 'collections.OrderedDict' object is not callable

**Comment by Karl-Krauth** [comment]
If you copy the latest example from the README you should be able to use it now. :)
