### ISSUE TITLE
Error in installing dependencies on MAC OS

### ISSUE THREAD

**Issue by r4n4sh** [berkeley-reclab/RecLab#226]
Hi, 
I got the following error when I tried to install the recommenders on MAC OS:

(base) ranashahout@Ranas-MacBook-Pro-2 3.10-dev % pip install reclab[recommenders]

zsh: no matches found: reclab[recommenders]

I already have g++ 5.0  and python3-dev installed.
Thank you

**Comment by k-rl** [comment]
It looks like this is due to the way zsh interprets square brackets. Try escaping them as follows:
`pip install reclab\[recommenders\]`
